# Generated by Django 2.0.2 on 2018-02-16 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bond',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=10)),
                ('shares', models.IntegerField()),
                ('coupon', models.DecimalField(decimal_places=1, max_digits=20)),
                ('yield_amt', models.DecimalField(decimal_places=1, max_digits=9)),
            ],
        ),
        migrations.AlterField(
            model_name='stock',
            name='current_price',
            field=models.DecimalField(decimal_places=1, max_digits=20),
        ),
        migrations.AlterField(
            model_name='stock',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stock',
            name='purchase_price',
            field=models.DecimalField(decimal_places=1, max_digits=20),
        ),
        migrations.AlterField(
            model_name='stock',
            name='shares',
            field=models.IntegerField(),
        ),
    ]
