# Generated by Django 2.0.2 on 2018-02-20 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
