# Generated by Django 2.0.2 on 2018-02-22 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0003_auto_20180221_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toppings',
            name='pizza',
            field=models.CharField(max_length=100),
        ),
    ]
